variables:
    AUDIT_AWS_EC2_ALERT_LIST:
        required: false
        type: array
        default:
            - ec2-inventory-instances # not_violation 
            - ec2-inventory-security-groups # not_violation 
            - ec2-ip-address-whitelisted # 
            - ec2-unrestricted-traffic # 
            - ec2-TCP-23 # 
            - ec2-TCP-21 # 
            - ec2-TCP-20 # 
            - ec2-ports-range # 
            - ec2-not-used-security-groups # 
            - ec2-default-security-group-traffic # cis_id:4.4 
            - ec2-vpc-flow-logs # cis_id:4.3 
#             - ec2-security-groups-list # not_violation 
#             - ec2-instances-active-security-groups-list # not_violation 
#             - elb-load-balancers-active-security-groups-list # not_violation 
#             - vpc-inventory # not_violation 
#             - flow-logs-inventory # not_violation 
        description: "Which rules would you like to run? Possible values are ec2-inventory-instances ec2-inventory-security-groups ec2-ip-address-whitelisted ec2-unrestricted-traffic     ec2-TCP-23 ec2-TCP-21 ec2-TCP-20 ec2-ports-range ec2-not-used-security-groups ec2-default-security-group-traffic ec2-vpc-flow-logs"
