variables:
    AUDIT_AWS_EC2_ALERT_LIST:
        required: false
        type: array
        default:
#             - elb-load-balancers-active-security-groups-list # not_violation 
#             - vpc-inventory # not_violation 
#             - flow-logs-inventory # not_violation 
        description: "Which rules would you like to run? Possible values are "
